--
-- PostgreSQL database dump
--

-- Dumped from database version 11.6
-- Dumped by pg_dump version 14.6

-- Started on 2025-08-18 11:20:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2963 (class 1262 OID 50652)
-- Name: smu; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE smu WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'Portuguese_Brazil.1252';


ALTER DATABASE smu OWNER TO postgres;

\connect smu

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 2964 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- TOC entry 610 (class 1247 OID 50659)
-- Name: tipo_usuario_enum; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.tipo_usuario_enum AS ENUM (
    'ALUNO',
    'MONITOR'
);


ALTER TYPE public.tipo_usuario_enum OWNER TO postgres;

SET default_tablespace = '';

--
-- TOC entry 217 (class 1259 OID 50992)
-- Name: aluno_disciplina; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.aluno_disciplina (
    aluno_id integer NOT NULL,
    disciplina_id integer NOT NULL
);


ALTER TABLE public.aluno_disciplina OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 50770)
-- Name: avaliacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.avaliacao (
    avaliacao_id bigint NOT NULL,
    comentario text,
    estrelas integer NOT NULL,
    aluno integer NOT NULL,
    sessao integer NOT NULL
);


ALTER TABLE public.avaliacao OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 50768)
-- Name: avaliacao_avaliacao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.avaliacao ALTER COLUMN avaliacao_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.avaliacao_avaliacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 197 (class 1259 OID 50725)
-- Name: curso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.curso (
    id_curso integer NOT NULL,
    codigo character varying(255) NOT NULL,
    nome character varying(255) NOT NULL
);


ALTER TABLE public.curso OWNER TO postgres;

--
-- TOC entry 196 (class 1259 OID 50723)
-- Name: curso_id_curso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.curso_id_curso_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.curso_id_curso_seq OWNER TO postgres;

--
-- TOC entry 2965 (class 0 OID 0)
-- Dependencies: 196
-- Name: curso_id_curso_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.curso_id_curso_seq OWNED BY public.curso.id_curso;


--
-- TOC entry 199 (class 1259 OID 50733)
-- Name: disciplina; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.disciplina (
    id_disciplina integer NOT NULL,
    nome character varying(255) NOT NULL,
    codigo character varying(255) NOT NULL,
    curso_id integer
);


ALTER TABLE public.disciplina OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 50731)
-- Name: disciplina_id_disciplina_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.disciplina_id_disciplina_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.disciplina_id_disciplina_seq OWNER TO postgres;

--
-- TOC entry 2966 (class 0 OID 0)
-- Dependencies: 198
-- Name: disciplina_id_disciplina_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.disciplina_id_disciplina_seq OWNED BY public.disciplina.id_disciplina;


--
-- TOC entry 205 (class 1259 OID 50788)
-- Name: material; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.material (
    id_material integer NOT NULL,
    arquivo character varying(255),
    data_envio timestamp(6) without time zone,
    descricao character varying(255),
    link character varying(255),
    titulo character varying(255),
    monitoria_id integer
);


ALTER TABLE public.material OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 50786)
-- Name: material_id_material_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.material ALTER COLUMN id_material ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.material_id_material_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 50798)
-- Name: mensagem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mensagem (
    mensagem_id integer NOT NULL,
    conteudo character varying(255),
    data_hora timestamp(6) without time zone,
    autor integer,
    sessao integer
);


ALTER TABLE public.mensagem OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 50796)
-- Name: mensagem_mensagem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mensagem ALTER COLUMN mensagem_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensagem_mensagem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 50805)
-- Name: monitoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.monitoria (
    id_monitoria integer NOT NULL,
    dias_da_semana character varying(50),
    horario time(6) without time zone,
    link character varying(255),
    nome character varying(255),
    curso_id integer,
    disciplina_id integer,
    monitor_id integer
);


ALTER TABLE public.monitoria OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 50803)
-- Name: monitoria_id_monitoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.monitoria ALTER COLUMN id_monitoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.monitoria_id_monitoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 50815)
-- Name: notificacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notificacao (
    notificacaoid integer NOT NULL,
    horario timestamp(6) without time zone,
    lida boolean NOT NULL,
    mensagem character varying(255),
    destinatario integer
);


ALTER TABLE public.notificacao OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 50813)
-- Name: notificacao_notificacaoid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notificacao ALTER COLUMN notificacaoid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificacao_notificacaoid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 50822)
-- Name: sessao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessao (
    id_sessao integer NOT NULL,
    horario timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    monitoria_id integer,
    CONSTRAINT sessao_status_check CHECK (((status)::text = ANY ((ARRAY['ANALISE'::character varying, 'DEFERIDA'::character varying, 'RECUSADA'::character varying])::text[])))
);


ALTER TABLE public.sessao OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 50820)
-- Name: sessao_id_sessao_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sessao ALTER COLUMN id_sessao ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessao_id_sessao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 50748)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario integer NOT NULL,
    nome character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    senha character varying(255) NOT NULL,
    matricula character varying(255) NOT NULL,
    data_nascimento date NOT NULL,
    tipo character varying(255) NOT NULL,
    curso_id integer,
    disciplina_id integer
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 50850)
-- Name: usuario_disciplina; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_disciplina (
    usuario_id integer NOT NULL,
    disciplina_id integer NOT NULL
);


ALTER TABLE public.usuario_disciplina OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 50746)
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuario_id_usuario_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuario_id_usuario_seq OWNER TO postgres;

--
-- TOC entry 2967 (class 0 OID 0)
-- Dependencies: 200
-- Name: usuario_id_usuario_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuario_id_usuario_seq OWNED BY public.usuario.id_usuario;


--
-- TOC entry 215 (class 1259 OID 50855)
-- Name: usuario_monitoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_monitoria (
    usuario_id integer NOT NULL,
    monitoria_id integer NOT NULL
);


ALTER TABLE public.usuario_monitoria OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 50860)
-- Name: usuario_sessao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_sessao (
    usuario_id integer NOT NULL,
    sessao_id integer NOT NULL
);


ALTER TABLE public.usuario_sessao OWNER TO postgres;

--
-- TOC entry 2758 (class 2604 OID 50728)
-- Name: curso id_curso; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curso ALTER COLUMN id_curso SET DEFAULT nextval('public.curso_id_curso_seq'::regclass);


--
-- TOC entry 2759 (class 2604 OID 50736)
-- Name: disciplina id_disciplina; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplina ALTER COLUMN id_disciplina SET DEFAULT nextval('public.disciplina_id_disciplina_seq'::regclass);


--
-- TOC entry 2760 (class 2604 OID 50751)
-- Name: usuario id_usuario; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario ALTER COLUMN id_usuario SET DEFAULT nextval('public.usuario_id_usuario_seq'::regclass);


--
-- TOC entry 2957 (class 0 OID 50992)
-- Dependencies: 217
-- Data for Name: aluno_disciplina; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.aluno_disciplina (aluno_id, disciplina_id) FROM stdin;
\.


--
-- TOC entry 2943 (class 0 OID 50770)
-- Dependencies: 203
-- Data for Name: avaliacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.avaliacao (avaliacao_id, comentario, estrelas, aluno, sessao) FROM stdin;
\.


--
-- TOC entry 2937 (class 0 OID 50725)
-- Dependencies: 197
-- Data for Name: curso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.curso (id_curso, codigo, nome) FROM stdin;
3	ESW001	Engenharia de Software
\.


--
-- TOC entry 2939 (class 0 OID 50733)
-- Dependencies: 199
-- Data for Name: disciplina; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.disciplina (id_disciplina, nome, codigo, curso_id) FROM stdin;
\.


--
-- TOC entry 2945 (class 0 OID 50788)
-- Dependencies: 205
-- Data for Name: material; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.material (id_material, arquivo, data_envio, descricao, link, titulo, monitoria_id) FROM stdin;
\.


--
-- TOC entry 2947 (class 0 OID 50798)
-- Dependencies: 207
-- Data for Name: mensagem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mensagem (mensagem_id, conteudo, data_hora, autor, sessao) FROM stdin;
\.


--
-- TOC entry 2949 (class 0 OID 50805)
-- Dependencies: 209
-- Data for Name: monitoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.monitoria (id_monitoria, dias_da_semana, horario, link, nome, curso_id, disciplina_id, monitor_id) FROM stdin;
\.


--
-- TOC entry 2951 (class 0 OID 50815)
-- Dependencies: 211
-- Data for Name: notificacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notificacao (notificacaoid, horario, lida, mensagem, destinatario) FROM stdin;
\.


--
-- TOC entry 2953 (class 0 OID 50822)
-- Dependencies: 213
-- Data for Name: sessao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessao (id_sessao, horario, status, monitoria_id) FROM stdin;
\.


--
-- TOC entry 2941 (class 0 OID 50748)
-- Dependencies: 201
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id_usuario, nome, email, senha, matricula, data_nascimento, tipo, curso_id, disciplina_id) FROM stdin;
1	João Silva	joao.silva@example.com	senhaSegura123	2025123456	1995-08-10	ALUNO	3	\N
\.


--
-- TOC entry 2954 (class 0 OID 50850)
-- Dependencies: 214
-- Data for Name: usuario_disciplina; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario_disciplina (usuario_id, disciplina_id) FROM stdin;
\.


--
-- TOC entry 2955 (class 0 OID 50855)
-- Dependencies: 215
-- Data for Name: usuario_monitoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario_monitoria (usuario_id, monitoria_id) FROM stdin;
\.


--
-- TOC entry 2956 (class 0 OID 50860)
-- Dependencies: 216
-- Data for Name: usuario_sessao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario_sessao (usuario_id, sessao_id) FROM stdin;
\.


--
-- TOC entry 2968 (class 0 OID 0)
-- Dependencies: 202
-- Name: avaliacao_avaliacao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.avaliacao_avaliacao_id_seq', 1, false);


--
-- TOC entry 2969 (class 0 OID 0)
-- Dependencies: 196
-- Name: curso_id_curso_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.curso_id_curso_seq', 3, true);


--
-- TOC entry 2970 (class 0 OID 0)
-- Dependencies: 198
-- Name: disciplina_id_disciplina_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.disciplina_id_disciplina_seq', 1, false);


--
-- TOC entry 2971 (class 0 OID 0)
-- Dependencies: 204
-- Name: material_id_material_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.material_id_material_seq', 1, false);


--
-- TOC entry 2972 (class 0 OID 0)
-- Dependencies: 206
-- Name: mensagem_mensagem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mensagem_mensagem_id_seq', 1, false);


--
-- TOC entry 2973 (class 0 OID 0)
-- Dependencies: 208
-- Name: monitoria_id_monitoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.monitoria_id_monitoria_seq', 1, false);


--
-- TOC entry 2974 (class 0 OID 0)
-- Dependencies: 210
-- Name: notificacao_notificacaoid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notificacao_notificacaoid_seq', 1, false);


--
-- TOC entry 2975 (class 0 OID 0)
-- Dependencies: 212
-- Name: sessao_id_sessao_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sessao_id_sessao_seq', 1, false);


--
-- TOC entry 2976 (class 0 OID 0)
-- Dependencies: 200
-- Name: usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_usuario_seq', 1, true);


--
-- TOC entry 2793 (class 2606 OID 50996)
-- Name: aluno_disciplina aluno_disciplina_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aluno_disciplina
    ADD CONSTRAINT aluno_disciplina_pkey PRIMARY KEY (aluno_id, disciplina_id);


--
-- TOC entry 2775 (class 2606 OID 50777)
-- Name: avaliacao avaliacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avaliacao
    ADD CONSTRAINT avaliacao_pkey PRIMARY KEY (avaliacao_id);


--
-- TOC entry 2763 (class 2606 OID 50730)
-- Name: curso curso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curso
    ADD CONSTRAINT curso_pkey PRIMARY KEY (id_curso);


--
-- TOC entry 2765 (class 2606 OID 50782)
-- Name: disciplina disciplina_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplina
    ADD CONSTRAINT disciplina_codigo_key UNIQUE (codigo);


--
-- TOC entry 2767 (class 2606 OID 50738)
-- Name: disciplina disciplina_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplina
    ADD CONSTRAINT disciplina_pkey PRIMARY KEY (id_disciplina);


--
-- TOC entry 2777 (class 2606 OID 50795)
-- Name: material material_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT material_pkey PRIMARY KEY (id_material);


--
-- TOC entry 2779 (class 2606 OID 50802)
-- Name: mensagem mensagem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensagem
    ADD CONSTRAINT mensagem_pkey PRIMARY KEY (mensagem_id);


--
-- TOC entry 2781 (class 2606 OID 50812)
-- Name: monitoria monitoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monitoria
    ADD CONSTRAINT monitoria_pkey PRIMARY KEY (id_monitoria);


--
-- TOC entry 2783 (class 2606 OID 50819)
-- Name: notificacao notificacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificacao
    ADD CONSTRAINT notificacao_pkey PRIMARY KEY (notificacaoid);


--
-- TOC entry 2785 (class 2606 OID 50827)
-- Name: sessao sessao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessao
    ADD CONSTRAINT sessao_pkey PRIMARY KEY (id_sessao);


--
-- TOC entry 2787 (class 2606 OID 50854)
-- Name: usuario_disciplina usuario_disciplina_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_disciplina
    ADD CONSTRAINT usuario_disciplina_pkey PRIMARY KEY (usuario_id, disciplina_id);


--
-- TOC entry 2769 (class 2606 OID 50835)
-- Name: usuario usuario_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_email_key UNIQUE (email);


--
-- TOC entry 2771 (class 2606 OID 50840)
-- Name: usuario usuario_matricula_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_matricula_key UNIQUE (matricula);


--
-- TOC entry 2789 (class 2606 OID 50859)
-- Name: usuario_monitoria usuario_monitoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_monitoria
    ADD CONSTRAINT usuario_monitoria_pkey PRIMARY KEY (usuario_id, monitoria_id);


--
-- TOC entry 2773 (class 2606 OID 50753)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


--
-- TOC entry 2791 (class 2606 OID 50864)
-- Name: usuario_sessao usuario_sessao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_sessao
    ADD CONSTRAINT usuario_sessao_pkey PRIMARY KEY (usuario_id, sessao_id);


--
-- TOC entry 2813 (class 2606 OID 50997)
-- Name: aluno_disciplina aluno_disciplina_aluno_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aluno_disciplina
    ADD CONSTRAINT aluno_disciplina_aluno_id_fkey FOREIGN KEY (aluno_id) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 2814 (class 2606 OID 51002)
-- Name: aluno_disciplina aluno_disciplina_disciplina_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aluno_disciplina
    ADD CONSTRAINT aluno_disciplina_disciplina_id_fkey FOREIGN KEY (disciplina_id) REFERENCES public.disciplina(id_disciplina);


--
-- TOC entry 2794 (class 2606 OID 50741)
-- Name: disciplina disciplina_curso_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplina
    ADD CONSTRAINT disciplina_curso_id_fkey FOREIGN KEY (curso_id) REFERENCES public.curso(id_curso);


--
-- TOC entry 2805 (class 2606 OID 50905)
-- Name: notificacao fk4vldcg9hv3fj5gbb074donn5q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificacao
    ADD CONSTRAINT fk4vldcg9hv3fj5gbb074donn5q FOREIGN KEY (destinatario) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 2811 (class 2606 OID 50935)
-- Name: usuario_sessao fk55uact2t0twldprg4c8qi00tv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_sessao
    ADD CONSTRAINT fk55uact2t0twldprg4c8qi00tv FOREIGN KEY (sessao_id) REFERENCES public.sessao(id_sessao);


--
-- TOC entry 2802 (class 2606 OID 50890)
-- Name: monitoria fk6rm5y6f5v7tn3gauvmvk80f7d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monitoria
    ADD CONSTRAINT fk6rm5y6f5v7tn3gauvmvk80f7d FOREIGN KEY (curso_id) REFERENCES public.curso(id_curso);


--
-- TOC entry 2798 (class 2606 OID 50870)
-- Name: avaliacao fk7mtx9efcouygylhvs7i7j2a8n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avaliacao
    ADD CONSTRAINT fk7mtx9efcouygylhvs7i7j2a8n FOREIGN KEY (sessao) REFERENCES public.sessao(id_sessao);


--
-- TOC entry 2809 (class 2606 OID 50925)
-- Name: usuario_monitoria fk7onnb21edii4q9gq0v9tc7l0d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_monitoria
    ADD CONSTRAINT fk7onnb21edii4q9gq0v9tc7l0d FOREIGN KEY (monitoria_id) REFERENCES public.monitoria(id_monitoria);


--
-- TOC entry 2801 (class 2606 OID 50885)
-- Name: mensagem fk8ux8kthhcewxaljjvbj2cgxlu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensagem
    ADD CONSTRAINT fk8ux8kthhcewxaljjvbj2cgxlu FOREIGN KEY (sessao) REFERENCES public.sessao(id_sessao);


--
-- TOC entry 2799 (class 2606 OID 50875)
-- Name: material fk9w89uyal14fh93bcjxff9dbtg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT fk9w89uyal14fh93bcjxff9dbtg FOREIGN KEY (monitoria_id) REFERENCES public.monitoria(id_monitoria);


--
-- TOC entry 2807 (class 2606 OID 50915)
-- Name: usuario_disciplina fkc5vbk0c31haaqb29t515uqw37; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_disciplina
    ADD CONSTRAINT fkc5vbk0c31haaqb29t515uqw37 FOREIGN KEY (disciplina_id) REFERENCES public.disciplina(id_disciplina);


--
-- TOC entry 2804 (class 2606 OID 50900)
-- Name: monitoria fkd1dhr5him27u9vm6vumc6tmpe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monitoria
    ADD CONSTRAINT fkd1dhr5him27u9vm6vumc6tmpe FOREIGN KEY (monitor_id) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 2810 (class 2606 OID 50930)
-- Name: usuario_monitoria fkh6bqchwo9acj8xdha2m34inmb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_monitoria
    ADD CONSTRAINT fkh6bqchwo9acj8xdha2m34inmb FOREIGN KEY (usuario_id) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 2797 (class 2606 OID 50865)
-- Name: avaliacao fkorojeljfw1uydvoj8j8xahyt8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.avaliacao
    ADD CONSTRAINT fkorojeljfw1uydvoj8j8xahyt8 FOREIGN KEY (aluno) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 2803 (class 2606 OID 50895)
-- Name: monitoria fkpubdh3bcky9qon7hm4sg18yb1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monitoria
    ADD CONSTRAINT fkpubdh3bcky9qon7hm4sg18yb1 FOREIGN KEY (disciplina_id) REFERENCES public.disciplina(id_disciplina);


--
-- TOC entry 2812 (class 2606 OID 50940)
-- Name: usuario_sessao fkrociduutxajtf2hnaytww21jr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_sessao
    ADD CONSTRAINT fkrociduutxajtf2hnaytww21jr FOREIGN KEY (usuario_id) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 2800 (class 2606 OID 50880)
-- Name: mensagem fksh935vejnrsrjvp3mta39w646; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensagem
    ADD CONSTRAINT fksh935vejnrsrjvp3mta39w646 FOREIGN KEY (autor) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 2808 (class 2606 OID 50920)
-- Name: usuario_disciplina fksk1ltr59imgcto0s2h8sj9ywn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_disciplina
    ADD CONSTRAINT fksk1ltr59imgcto0s2h8sj9ywn FOREIGN KEY (usuario_id) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 2806 (class 2606 OID 50910)
-- Name: sessao fksx0otani1lrq73jbwrs16a5pc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessao
    ADD CONSTRAINT fksx0otani1lrq73jbwrs16a5pc FOREIGN KEY (monitoria_id) REFERENCES public.monitoria(id_monitoria);


--
-- TOC entry 2795 (class 2606 OID 50758)
-- Name: usuario usuario_curso_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_curso_id_fkey FOREIGN KEY (curso_id) REFERENCES public.curso(id_curso);


--
-- TOC entry 2796 (class 2606 OID 50763)
-- Name: usuario usuario_disciplina_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_disciplina_id_fkey FOREIGN KEY (disciplina_id) REFERENCES public.disciplina(id_disciplina);


-- Completed on 2025-08-18 11:20:58

--
-- PostgreSQL database dump complete
--

